[package]
name = "reconnaissance"
version = "0.1.0"
edition = "2024"

[dependencies]
tfhe = { version = "~1.3.3", features = ["integer", "boolean"] }
anyhow = "1.0.99"
npy = "0.4.0"
npyz = {version = "0.8", features = ["derive", "complex", "npz", "arrayvec", "half"]}